### PR TITLE
empty_object logic fix and Dor::Item find druid fix

### LINKED ISSUE #306: is discovery report empty_object logic backwards?
this seemed odd to me:
https://github.com/sul-dlss/pre-assembly/blob/master/app/services/discovery_report.rb#L55
```ruby
errors[:empty_object] = true if counts[:total_size] > 0
```

maybe i'm wrong, but wanted to capture that for investigation so it doesn't get lost.

noticed while reviewing a PR that didn't actually touch that line: https://github.com/sul-dlss/pre-assembly/pull/276#discussion_r218264402

### PR DESCRIPTION
**Pull request by SaravShah**
- Dor::Item find takes in a druid not druid tool object
- empty_object logic was backwards
- 2 RSpec tests to test the fixed logic.

closes #306 
connects #237

### CODE REVIEW

File: app/services/discovery_report.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@ def process_dobj(dobj)
   # @return [Hash<Symbol => Boolean>] errors
   def registration_check(druid)
     begin
-      obj = Dor::Item.find(druid)
+      obj = Dor::Item.find(druid.druid)
```
Comment (atz) [inline app/services/discovery_report.rb]: This doesn't match the documented signature of the method.  I.E., either need to:
- update line 62 about what is a valid parameter
- have line 58 call `registration_check(dobj.druid.druid)` (probably simplest)

File: spec/services/discovery_report_spec.rb [hunk 2]
```diff
@@ -55,5 +55,59 @@
...
+        content_metadata_creation: 0,
+        user: build(:user, sunet_id: 'jdoe@stanford.edu')
+      }
+    end
+    let(:bundle_context) {BundleContext.new(bc_params) }
+    let(:bundle) { PreAssembly::Bundle.new(bundle_context) }
+    let(:dobj) { report.bundle.objects_to_process.first }
+
+    before do
+      bundle.manifest_rows.each { |row| row.merge!("object" => row["folder"]) }
```
Comment (ndushay) [inline spec/services/discovery_report_spec.rb]: this line isn't be needed any longer - please remove it  (you may need to rebase first)
