### PR TITLE
Remove error as separate job run state.

### LINKED ISSUE #1301: If Preassembly has failed, status should not be reported as "accessioning complete"
**Describe the bug**
If there's an error in Preassembly, we shouldn't report "Accessioning completed". This happened on a Preassembly job run in stage: https://sul-preassembly-stage.stanford.edu/job_runs/3145

Screenshot 2023-09-22 at 3 12 37 PM

I'm not sure what statuses are available to report instead. In this case, there was only one druid and the druid failed before accessioning began.

We could say:

- Accessioning completed (with errors)
- Preassembly completed (with errors)

Or we could take a different tack and instead of distinguishing Accessioning and Preassembly, report it as 

- Job completed (with errors)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1301

# Why was this change made? 🤔
Make error state less confusing to users. This approach separates the presence of errors from the state.

# How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit, Andrew

# Does your change introduce accessibility violations? 🩺

⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more detail. ⚡

### CODE REVIEW

File: app/models/job_run.rb [hunk 1]
```diff
@@ -97,6 +91,16 @@ def file_manifest
                                   staging_location: batch_context.staging_location)
   end
 
+  def human_state_name_with_preassembly_errors
+    return human_state_name unless with_preassembly_errors?
+
+    "#{human_state_name} (with preassembly errors)"
+  end
+
```
Comment (peetucket) [inline app/models/job_run.rb:99]: Is there a more seamless way to do this?  Like can we just override the method state machine `human_state_name` method here and then use `super unless with_preassembly_errors?` in line 95?   Otherwise I can see being confused in the future by `job_run.human_state_name_with_preassembly_errors` conveying any possible state name.

Comment (justinlittman) [reply app/models/job_run.rb:99]: Changed.

**Review by peetucket — APPROVED** [review]

File: db/schema.rb [hunk 2]
```diff
@@ -58,6 +58,7 @@
     t.datetime "updated_at", precision: nil, null: false
     t.string "state", default: "waiting", null: false
     t.text "error_message"
+    t.jsonb "objects_with_error", default: [], null: false
```
Comment (jmartin-sul) [inline db/schema.rb:61]: i don't see anything in the migration about adding this column... cruft from a prior iteration, or am i missing something?

File: spec/features/discovery_report/completed_with_errors_spec.rb [hunk 3]
```diff
@@ -41,7 +41,7 @@
     # go to job details page, wait for preassembly to finish
     first('td  > a').click
     expect(page).to have_content project_name
-    expect(page).to have_content 'Discovery report completed (with errors)'
+    expect(page).to have_content 'Discovery report completed (with preassembly errors)'
```
Comment (jmartin-sul) [inline spec/features/discovery_report/completed_with_errors_spec.rb:44]: this seems like a weird bit of text to have for the discovery report.  could `JobRun#human_state_name` either do something more generic for the parenthetical, or pick `discovery report` or `preassembly` for the text based on the job type?  i actually might vote for the former, since it's simpler and surrounding context should fill in that info fine?  "Discovery report completed (with errors)" seems sufficiently informative?

File: app/models/job_run.rb [hunk 4]
```diff
@@ -97,6 +91,16 @@ def file_manifest
                                   staging_location: batch_context.staging_location)
   end
 
+  def human_state_name
+    return super unless with_preassembly_errors?
+
+    "#{super} (with preassembly errors)"
+  end
+
+  def with_preassembly_errors?
```
Comment (jmartin-sul) [inline app/models/job_run.rb:100]: maybe this should just be a more generic `with_errors?` or `has_errors?` since it seems like it could apply to both discovery report jobs and preassembly jobs?

**Review by jmartin-sul — CHANGES_REQUESTED** [review]
some small quibbles about text and method name stuff, and i might've spotted a bit of database migration cruft from an iteration that wasn't the final version of this PR.

File: app/models/job_run.rb (hunk 4 above)
Comment (justinlittman) [reply app/models/job_run.rb:100]: Unfortunately the term preassembly is overloaded in this app. In this case, "preassembly" means errors in discovery report jobs or preassembly jobs (as opposed to an error in accessioning).

File: spec/features/discovery_report/completed_with_errors_spec.rb (hunk 3 above)
Comment (andrewjbtw) [reply spec/features/discovery_report/completed_with_errors_spec.rb:44]: Yes. I don't think it's possible to have preassembly errors in a discovery report. The discovery report runs on its own.

File: app/models/job_run.rb (hunk 4 above)
Comment (justinlittman) [reply app/models/job_run.rb:87]: Added method documentation to make clearer.

File: spec/features/discovery_report/completed_with_errors_spec.rb (hunk 3 above)
Comment (justinlittman) [reply spec/features/discovery_report/completed_with_errors_spec.rb:44]: https://github.com/sul-dlss/pre-assembly/issues/1316

**Review by jmartin-sul — APPROVED** [review]
