### PR TITLE
Do not email when preassembly job has no errors. Include druids in em…

### LINKED ISSUE #1261: Email when Preassembly fails
In order to preserve space Preassembly runs each object through Preassembly and Accessioning serially. So if a `JobRun` is configured to update 3 SDR Items it will:

1. Preassemble A
2. Accession A (non-blocking)
3. Preassemble B
4. Accession B (non-blocking)
5. Preassemble C
6. Accession C (non-blocking)
7. Send Accessioning Complete email when A, B and C are completed.

However if Preaccessioning fails for B and C, Accessioning for B and C will never occur, and the completion email will not mention them. 

To help handle this situation Preassembly should send an email to the user if any items in their Job fail in Preassembly which will let them know that they will want to reconfigure their Preassembly job.

The text of the email should read:

```
The configuration for {number-of-failed-items} in your Preassembly job failed to complete setup. Please see {JobRun URL} for details or contact {repository-manager-email}.
```

### PR DESCRIPTION
**Pull request by justinlittman**
…ail.

closes #1261

# Why was this change made? 🤔

# How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or how it uses APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] environment, in addition to specs. ⚡

Unit, Andrew

# Does your change introduce accessibility violations? 🩺

⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more detail. ⚡

### CODE REVIEW

File: app/jobs/preassembly_job.rb [hunk 1]
```diff
@@ -7,7 +7,13 @@ def perform(job_run)
     batch = job_run.batch
     # .run_pre_assembly iterates over all objects and runs preassembly on each
     batch.run_pre_assembly
-    job_run.error_message = batch.objects_had_errors ? batch.error_message : nil
+    if batch.objects_had_errors?
+      job_run.error_message = batch.error_message
+      job_run.objects_with_error = batch.objects_with_error
```
Comment (justinlittman) [inline app/jobs/preassembly_job.rb:12]: Added the druids with errors to the job run model object to be persisted.

File: app/services/discovery_report.rb [hunk 2]
```diff
@@ -15,7 +14,7 @@ def initialize(batch)
     raise ArgumentError unless batch.is_a?(PreAssembly::Batch)
 
     @batch = batch
-    @summary = { objects_with_error: 0, mimetypes: Hash.new(0), start_time: Time.now.utc.to_s, total_size: 0 }
+    @summary = { objects_with_error: [], mimetypes: Hash.new(0), start_time: Time.now.utc.to_s, total_size: 0 }
```
Comment (justinlittman) [inline app/services/discovery_report.rb:17]: Now keeps track of druids of objects with errors.

**Review by aaron-collier — APPROVED** [review]

File: config/settings.yml [hunk 3]
```diff
@@ -11,8 +11,9 @@ dor_services:
 expected_worker_count: 5 # for okcomputer endpoint
 
 mailer_host: 'localhost'
+repository_manager_email: CHANGE_ME@stanford.edu
```
[the remark this answers is not in the document]
Comment (edsu) [reply config/settings.yml]: I guess we should get the real email address before merging?

**Review by edsu — APPROVED** [review]
